### ISSUE TITLE
link to twitter from your blog?

### ISSUE THREAD

**Issue by ajschumacher** [briamkin/briamkin.github.io#2]
is it there? am I missing it? is it intentionally not there?

**Comment by briamkin** [comment]
Hmm good question! I was never much of a tweeter but maybe it's about time
I try hahah. Hopefully linking to it will make me want to tweet more!

**Comment by ajschumacher** [comment]
You don't even have to tweet, but it gives people who prefer twitter that
route to contact you if they want to.

**Comment by briamkin** [comment]
oo, gotya! I added it~
